### ISSUE TITLE
Issue with WineLauncher

### ISSUE THREAD

**Issue by dabvid** [Shenmue-Mods/Shenmue12launcher#2]
Followed the instruction and replaced the original launcher with the WineLauncher from release 1.01 and then renamed it.
Tried different way of open the game, sm2 as advanced argument etc.
Doesn't open. I'm on Crossover 20.0.4 - Windows 7 64

**Comment by Sappharad** [comment]
Install .NET Framework 4.x in the bottle.

**Comment by dabvid** [comment]
Thanks. Now the launcher is starting. So one step in the right direction.
The Shenmue 1 executable doesn't respond after launching though and Shenmue 2 crashes on launch.

**Comment by dabvid** [comment]
Did a reinstall of everything and now the games are starting as well so big thanks.
